### PR TITLE
Comparing two versions of CMFGEN dataset

### PR DESCRIPTION
**Pull request by s-rathi**
### :pencil: Comparing two versions of CMFGEN datasets

**Type:**  :rocket: `feature` |

This workflow compares two CMFGEN datasets by creating a hash of the new dataset and matching it with the hash of already available CMFGEN data.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [X] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [X] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by atharva-2001** [comment]
Hi Shikha, the changes look very good. Could you please make the PR title and commit messages more descriptive?

**Comment by wkerzendorf** [comment]
I think this looks great. I think for the future - it might be much easier if we run a notebook that does the steps - then you have access to the full power of python.

**Comment by s-rathi** [comment]
Thanks. I will try to use the notebook.

**Comment by atharva-2001** [comment]
Hi Shikha, I would look at this soon, but this seems to be going great. One small comment- could you please make commit messages more descriptive?

Commits should be small and should have messages describing them. Doing GitHub Actions requires you to make several small changes as you try the pipeline on the cloud, so they(messages) don’t have to be perfect!

**Comment by s-rathi** [comment]
Sorry Atharva, I apologise for the above commits without a description. however, these commits do not include many changes as I was testing just a small thing.

**Comment by atharva-2001** [comment]
```diff
+ 1
- 2

**Comment by atharva-2001** [comment]
This PR isn't needed, right?

**Pull request closed without merging**
